// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oprupztavrhfyeucrock.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wcnVwenRhdnJoZnlldWNyb2NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwOTQ5NDcsImV4cCI6MjA1ODY3MDk0N30.UPqBvnseSbN-G6P1lhD1CerAmMssPy4i6vXZaZqzciE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);